# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://david-waite.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: David Waite
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "David Waite Portfolio Programmer Ruby Rails" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Husband, Programmer, Runner, and aspiring beekeeper.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "Dwaite498@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "DaveyWaite"
  flickr:
  github: "dwaite498"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/david-waite2017/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "Dwaite498"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]